//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Box.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogContentList
    {
        public int blogId { get; set; }
        public string blogHeader { get; set; }
        public string contents { get; set; }
    }
}
