//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Box.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class up_skill_dbEntities1 : DbContext
    {
        public up_skill_dbEntities1()
            : base("name=up_skill_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<BlogContentList> BlogContentLists { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Courses_tb> Courses_tb { get; set; }
        public virtual DbSet<SideNavigationMenuAdmin_tb> SideNavigationMenuAdmin_tb { get; set; }
        public virtual DbSet<TopicDetails_tb> TopicDetails_tb { get; set; }
        public virtual DbSet<Vertical_Nav_tb> Vertical_Nav_tb { get; set; }
        public virtual DbSet<vertical_tab_list_tb> vertical_tab_list_tb { get; set; }
    }
}
