//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Box.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicDetails_tb
    {
        public int TopicDetailsId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string TopicName { get; set; }
        public string TechnologyType { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TopicDetails { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string TopicPath { get; set; }
    
        public virtual Courses_tb Courses_tb { get; set; }
        public virtual Vertical_Nav_tb Vertical_Nav_tb { get; set; }
    }
}
